//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day8.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 11 7 3 5 4 3 5 1 7 0 11 7 1 2 1 9 4 6 9 5 8 1 2 1 1 1 2 1 3 1 5 0 6 6 2 4 1 3 9 2 1 3 3 1 1 8 0 6 1 6 1 1 8 8 2 1 1 1 3 3 2 2 2 1 1 3 1 3 4 1 5 0 8 8 6 7 2 1 3 6 8 1 1 2 2 1 1 9 0 11 7 4 3 3 1 7 1 7 9 5 9 1 3 1 1 1 2 1 2 1 1 9 0 10 6 2 8 7 7 1 9 2 3 2 1 3 2 3 3 2 2 2 2 3 3 4 4 3 4 1 5 0 10 5 5 8 7 2 8 1 2 2 5 1 2 3 1 1 1 5 0 8 7 4 9 3 4 1 7 1 2 1 3 2 1 1 9 0 10 1 2 6 4 6 5 7 7 1 9 1 1 2 3 1 1 1 3 1 2 3 1 2 3 7 1 7 0 9 6 1 3 4 7 2 8 7 5 2 2 2 1 1 1 1 1 7 0 7 1 4 6 7 2 3 3 2 1 1 3 1 1 2 1 8 0 7 1 7 4 5 5 5  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
    }
}
