//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +13
        ///-12
        ///-14
        ///+19
        ///-13
        ///+16
        ///+12
        ///+19
        ///+8
        ///-10
        ///-9
        ///-2
        ///+1
        ///-13
        ///+10
        ///-7
        ///-11
        ///-10
        ///+1
        ///-14
        ///-15
        ///+16
        ///+6
        ///+17
        ///-19
        ///-13
        ///+5
        ///-19
        ///-12
        ///-10
        ///-12
        ///+13
        ///+14
        ///+3
        ///-13
        ///+3
        ///+17
        ///+10
        ///-16
        ///+19
        ///+1
        ///+11
        ///-16
        ///+3
        ///-16
        ///-12
        ///-7
        ///-11
        ///-6
        ///-19
        ///+6
        ///+12
        ///+15
        ///-7
        ///-18
        ///+13
        ///-4
        ///-14
        ///-7
        ///-18
        ///+17
        ///+9
        ///-12
        ///-3
        ///-13
        ///-16
        ///+14
        ///-4
        ///-12
        ///-10
        ///-3
        ///+8
        ///-10
        ///-4
        ///-10
        ///-11
        ///-14
        ///+11
        ///-7
        ///+17
        ///+19
        ///+2
        ///-13
        ///+17
        ///-10
        ///-6
        ///+15
        ///+7
        ///+15
        ///-3
        ///-7
        ///-6
        ///-1
        ///-13
        ///-5
        ///-6
        ///-6
        ///-12
        ///-18
        ///-7
        ///-19
        ///-5
        ///-15
        ///-7
        ///+4
        ///-18
        ///+5
        ///+17
        ///-2
        ///-12
        ///-1
        ///+3
        ///-11
        ///+10
        ///-13
        ///+10
        ///+17
        ///+15
        ///+16
        ///+16
        ///-7
        ///-17
        ///-11
        ///+10
        ///-15
        ///-13
        ///+2
        ///-6
        ///+3
        ///+9
        ///+2
        ///+20
        ///-14
        ///+22
        ///+6
        ///+14
        ///-3
        ///-15
        ///-7
        ///-16
        ///-2
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
    }
}
