//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day16.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day16.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before: [2, 0, 0, 1]
        ///15 3 1 3
        ///After:  [2, 0, 0, 1]
        ///
        ///Before: [3, 2, 3, 3]
        ///4 3 3 0
        ///After:  [3, 2, 3, 3]
        ///
        ///Before: [3, 2, 1, 3]
        ///12 3 0 0
        ///After:  [1, 2, 1, 3]
        ///
        ///Before: [1, 2, 2, 2]
        ///2 0 2 0
        ///After:  [0, 2, 2, 2]
        ///
        ///Before: [0, 1, 2, 1]
        ///10 1 0 1
        ///After:  [0, 1, 2, 1]
        ///
        ///Before: [2, 1, 3, 2]
        ///11 0 3 3
        ///After:  [2, 1, 3, 1]
        ///
        ///Before: [1, 2, 1, 1]
        ///9 2 0 2
        ///After:  [1, 2, 2, 1]
        ///
        ///Before: [3, 0, 1, 1]
        ///15 3 1 3
        ///After:  [3, 0, 1, 1]
        ///
        ///Before: [0, 1, 1, 1]
        ///10 1 0 3
        ///After:  [0, 1, 1, 1]
        ///
        ///Before: [1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input1 {
            get {
                return ResourceManager.GetString("input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 2 3 2
        ///15 1 0 1
        ///10 1 0 1
        ///2 0 1 3
        ///0 3 2 1
        ///15 1 1 1
        ///9 0 1 0
        ///14 0 2 2
        ///2 2 3 0
        ///2 1 2 1
        ///2 3 0 3
        ///1 1 0 0
        ///15 0 2 0
        ///15 0 2 0
        ///9 0 2 2
        ///14 2 3 1
        ///2 1 0 0
        ///15 1 0 2
        ///10 2 2 2
        ///2 2 0 3
        ///1 0 3 0
        ///15 0 1 0
        ///9 1 0 1
        ///14 1 2 3
        ///2 3 1 1
        ///2 1 0 0
        ///14 0 2 0
        ///15 0 2 0
        ///9 0 3 3
        ///14 3 1 1
        ///2 3 1 2
        ///2 1 2 3
        ///2 2 1 0
        ///1 3 0 2
        ///15 2 2 2
        ///9 2 1 1
        ///14 1 1 2
        ///2 1 3 0
        ///2 2 0 1
        ///2 3 1 3
        ///9 0 0 1
        ///15 1 1 1
        ///9 1 2 2
        ///14 2 0 1
        ///2 2 0 0
        ///2 2 0 3
        ///2 2 3 2
        ///11 0 3 0
        ///15 0 3 0
        ///9 0 1 1
        ///2 0 0 0
        ///2 0 3 2
        ///13 2 3 2
        ///15 2 1 2
        ///9 1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input2 {
            get {
                return ResourceManager.GetString("input2", resourceCulture);
            }
        }
    }
}
